### ISSUE TITLE
01_osumap_loader

### ISSUE THREAD

**Issue by ohitstom** [kotritrona/osumapper#12]
Number of filtered maps: 6
Error on #0, path = D:\Main Personal\Songs\979887 Teminite & MDK - Space Invaders\Teminite & MDK - Space Invaders (Ciyus Miapah) [Dimensional Virtual Arcade].osu, error = [Errno 2] No such file or directory: 'temp_json_file.json'
Error on #1, path = D:\Main Personal\Songs\185250 ALiCE'S EMOTiON - Dark Flight Dreamer\ALiCE'S EMOTiON - Dark Flight Dreamer (Sakaue Nachi) [CRN's Extra].osu, error = [Errno 2] No such file or directory: 'temp_json_file.json'
Error on #2, path = D:\Main Personal\Songs\740672 Ni-Sokkususu - Shukusai no Elementalia\Ni-Sokkususu - Shukusai no Elementalia (SnowNiNo_) [KNeeSocKs].osu, error = [Errno 2] No such file or directory: 'temp_json_file.json'
Error on #3, path = D:\Main Personal\Songs\693750 Shinonome Natsuhi (CV_ Hinami Yuri) - Moratorium no Oto\Shinonome Natsuhi (CV Hinami Yuri) - Moratorium no Oto (newton-) [Standstill].osu, error = [Errno 2] No such file or directory: 'temp_json_file.json'
Error on #4, path = D:\Main Personal\Songs\88180 t+pazolite - cheatreal\t+pazolite - cheatreal (caren_sk) [RLC's Extra].osu, error = [Errno 2] No such file or directory: 'temp_json_file.json'
Error on #5, path = D:\Main Personal\Songs\205425 Nujabes - Lady Brown (feat Cise Starr)\Nujabes - Lady Brown (feat. Cise Starr) (Mawkawa) [Extra].osu, error = [Errno 2] No such file or directory: 'temp_json_file.json'

**Comment by Commanvil** [comment]
similar problem

```Error on #0, path = , error = [WinError 2] The system cannot find the file specified
Error on #1, path = C:\Users\Schino\Downloads\osumapper\osumapper-master\v6.2\osumaptraining1\Camellia - Arcology On Permafrost (Mir) [Arctic Fusion].osu, error = [WinError 2] The system cannot find the file specified
Error on #2, path = C:\Users\Schino\Downloads\osumapper\osumapper-master\v6.2\osumaptraining1\Camellia - Arcology On Permafrost (Mir) [Mun's Extra].osu, error = [WinError 2] The system cannot find the file specified
Error on #3, path = C:\Users\Schino\Downloads\osumapper\osumapper-master\v6.2\osumaptraining1\Camellia - Bassline Yatteru w (Mir) [Line Line Line].osu, error = [WinError 2] The system cannot find the file specified
Error on #4, path = C:\Users\Schino\Downloads\osumapper\osumapper-master\v6.2\osumaptraining1\Camellia - KillerBeast (Mir) [Death Rave].osu, error = [WinError 2] The system cannot find the file specified
Error on #5, path = C:\Users\Schino\Downloads\osumapper\osumapper-master\v6.2\osumaptraining1\Camellia - KillerBeast (Mir) [Reform's Extra].osu, error = [WinError 2] The system cannot find the file specified
Error on #6, path = C:\Users\Schino\Downloads\osumapper\osumapper-master\v6.2\osumaptraining1\Camellia - KillerBeast (Mir) [thzz's Blaster].osu, error = [WinError 2] The system cannot find the file specified```

**Comment by kotritrona** [comment]
Hi, if you're still there, the new version has better error messages implemented. You can try v7.0.
