### ISSUE TITLE
gcolab when GPU is enabled gets out_of_memory or crashes saying it needs 11gb of memory

### ISSUE THREAD

**Issue by jvyden420** [kotritrona/osumapper#4]
Gotten from readme.md, use issues, they're literally meant for tracking bugs w

**Comment by kotritrona** [comment]
wwwwwwww

**Comment by jvyden420** [comment]
wwwwwwwwwwwwwwwwwwwwwwww

**Comment by kotritrona** [comment]
it seems this problem is because batch_size is too big, which consumes too much GPU memory.
set batch_size=20 can solve the problem in gcolab.
